# -*- coding: utf-8 -*-
"""mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cGHla6hg_w5o5QLGx_S2y8GNQAPGMhr
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# -----------------------
# PAGE CONFIG
# -----------------------
st.set_page_config(
    page_title="Bank Transaction Analysis",
    page_icon="📊",
    layout="wide"
)

# -----------------------
# TITLE
# -----------------------
st.title("🏦 Bank Transaction Analysis Dashboard")
st.markdown("""
This dashboard analyzes banking transactions and provides
insights into withdrawals, deposits, balances and transaction trends.
""")

# -----------------------
# FILE UPLOAD
# -----------------------
uploaded_file = st.file_uploader(
    "Upload Bank Transaction CSV File",
    type=["csv"]
)

if uploaded_file:

    df = pd.read_csv(uploaded_file)

    st.success("Dataset uploaded successfully!")

    # -----------------------
    # DATA PREVIEW
    # -----------------------
    st.header("📄 Dataset Preview")

    st.dataframe(df.head())

    # -----------------------
    # BASIC INFORMATION
    # -----------------------
    st.header("📌 Dataset Information")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Rows", df.shape[0])

    with col2:
        st.metric("Columns", df.shape[1])

    with col3:
        st.metric("Missing Values", df.isnull().sum().sum())

    # -----------------------
    # CLEANING
    # -----------------------
    withdrawal_col = None
    deposit_col = None
    balance_col = None

    for col in df.columns:

        if "WITHDRAW" in col.upper():
            withdrawal_col = col

        if "DEPOSIT" in col.upper():
            deposit_col = col

        if "BALANCE" in col.upper():
            balance_col = col

    if withdrawal_col:
        df[withdrawal_col] = pd.to_numeric(
            df[withdrawal_col],
            errors='coerce'
        )

    if deposit_col:
        df[deposit_col] = pd.to_numeric(
            df[deposit_col],
            errors='coerce'
        )

    if balance_col:
        df[balance_col] = pd.to_numeric(
            df[balance_col],
            errors='coerce'
        )

    # -----------------------
    # SUMMARY STATISTICS
    # -----------------------
    st.header("📊 Transaction Summary")

    total_withdrawal = (
        df[withdrawal_col].fillna(0).sum()
        if withdrawal_col else 0
    )

    total_deposit = (
        df[deposit_col].fillna(0).sum()
        if deposit_col else 0
    )

    current_balance = (
        df[balance_col].dropna().iloc[-1]
        if balance_col and not df[balance_col].dropna().empty
        else 0
    )

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Total Withdrawal",
        f"RM {total_withdrawal:,.2f}"
    )

    c2.metric(
        "Total Deposit",
        f"RM {total_deposit:,.2f}"
    )

    c3.metric(
        "Latest Balance",
        f"RM {current_balance:,.2f}"
    )

    # -----------------------
    # MISSING VALUES
    # -----------------------
    st.header("🔍 Missing Value Analysis")

    missing_df = pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum().values
    })

    st.dataframe(missing_df)

    # -----------------------
    # DESCRIPTIVE STATS
    # -----------------------
    st.header("📈 Statistical Summary")

    st.dataframe(df.describe())

    # -----------------------
    # DEPOSIT VS WITHDRAWAL
    # -----------------------
    if withdrawal_col and deposit_col:

        st.header("💸 Deposit vs Withdrawal")

        comparison = pd.DataFrame({
            "Type": ["Withdrawal", "Deposit"],
            "Amount": [
                total_withdrawal,
                total_deposit
            ]
        })

        fig = px.bar(
            comparison,
            x="Type",
            y="Amount",
            title="Deposit vs Withdrawal"
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    # -----------------------
    # MONTHLY TREND
    # -----------------------
    date_col = None

    for col in df.columns:
        if "DATE" in col.upper():
            date_col = col
            break

    if date_col and deposit_col:

        try:

            df[date_col] = pd.to_datetime(
                df[date_col],
                errors="coerce"
            )

            monthly = (
                df.groupby(
                    df[date_col].dt.to_period("M")
                )[deposit_col]
                .sum()
                .reset_index()
            )

            monthly[date_col] = (
                monthly[date_col]
                .astype(str)
            )

            st.header("📅 Monthly Deposit Trend")

            fig2 = px.line(
                monthly,
                x=date_col,
                y=deposit_col,
                markers=True
            )

            st.plotly_chart(
                fig2,
                use_container_width=True
            )

        except:
            pass

    # -----------------------
    # BALANCE TREND
    # -----------------------
    if balance_col:

        st.header("💰 Balance Trend")

        fig3 = go.Figure()

        fig3.add_trace(
            go.Scatter(
                y=df[balance_col],
                mode='lines'
            )
        )

        fig3.update_layout(
            title="Account Balance Over Transactions",
            xaxis_title="Transaction Number",
            yaxis_title="Balance"
        )

        st.plotly_chart(
            fig3,
            use_container_width=True
        )

    # -----------------------
    # TOP TRANSACTION DETAILS
    # -----------------------
    details_col = None

    for col in df.columns:
        if "DETAIL" in col.upper():
            details_col = col
            break

    if details_col:

        st.header("📝 Most Frequent Transaction Details")

        top_transactions = (
            df[details_col]
            .value_counts()
            .head(10)
        )

        fig4 = px.bar(
            x=top_transactions.values,
            y=top_transactions.index,
            orientation="h"
        )

        st.plotly_chart(
            fig4,
            use_container_width=True
        )

    # -----------------------
    # CORRELATION
    # -----------------------
    st.header("📉 Correlation Analysis")

    numeric_df = df.select_dtypes(
        include=["int64", "float64"]
    )

    if len(numeric_df.columns) > 1:

        corr = numeric_df.corr()

        fig5 = px.imshow(
            corr,
            text_auto=True,
            aspect="auto"
        )

        st.plotly_chart(
            fig5,
            use_container_width=True
        )

    # -----------------------
    # DOWNLOAD DATA
    # -----------------------
    st.header("⬇ Download Dataset")

    csv = df.to_csv(index=False)

    st.download_button(
        label="Download CSV",
        data=csv,
        file_name="cleaned_bank_data.csv",
        mime="text/csv"
    )

else:

    st.info("Please upload a CSV file to begin analysis.")